spring:
  application:
    name: music-library-90s
  config:
    import: "optional:file:./db_credentials.yaml"
  jackson:
    default-property-inclusion: NON_EMPTY
  profiles:
    active: dev


logging:
  level:
    root: warn