INSERT INTO songs (name, release_year, artist, album, track) VALUES
     ('Viva Forever', 1997, 'Spice Girls', 'Spiceworld', 9),
     ('Wannabe', 1996, 'Spice Girls', 'Spice', 1),
     ('Say You''ll Be There', 1996, 'Spice Girls', 'Spice', 2),
     ('Stop', 1997, 'Spice Girls', 'Spiceworld', 2),
     ('2 Become 1', 1996, 'Spice Girls', 'Spice', 3),
     ('Spice Up Your Life', 1997, 'Spice Girls', 'Spiceworld', 1),
     ('Smells Like Teen Spirit', 1991, 'Nirvana', 'Nevermind', 1),
     ('Come as You Are', 1991, 'Nirvana', 'Nevermind', 3),
     ('Lithium', 1991, 'Nirvana', 'Nevermind', 5),
     ('Heart-Shaped Box', 1993, 'Nirvana', 'In Utero', 3),
     ('Frozen', 1998, 'Madonna', 'Ray of Light', 9),
     ('Secret', 1994, 'Madonna', 'Bedtime Stories', 2),
     ('Everybody (Backstreet''s Back)', 1997, 'Backstreet Boys', 'Backstreet''s Back', 1),
     ('I Want It That Way', 1999, 'Backstreet Boys', 'Millennium', 1),
     ('I Want You Back', 1997, 'N''Sync', 'N''Sync', 1),
     ('Bye Bye Bye', 1999, 'N''Sync', 'No Strings Attached', 1)