INSERT INTO songs (name, release_year, artist, album, track) VALUES
     ('Wannabe', 1996, 'Spice Girls', 'Spice', 1),
     ('Say You''ll Be There', 1996, 'Spice Girls', 'Spice', 2),
     ('2 Become 1', 1996, 'Spice Girls', 'Spice', 3),
     ('Spice Up Your Life', 1997, 'Spice Girls', 'Spiceworld', 1),
     ('Smells Like Teen Spirit', 1991, 'Nirvana', 'Nevermind', 1),
     ('Come as You Are', 1991, 'Nirvana', 'Nevermind', 3),
     ('Lithium', 1991, 'Nirvana', 'Nevermind', 5),
     ('Heart-Shaped Box', 1993, 'Nirvana', 'In Utero', 3),
     ('Vogue', 1990, 'Madonna', 'I''m Breathless', 12),
     ('Frozen', 1998, 'Madonna', 'Ray of Light', 9),
     ('Ray of Light', 1998, 'Madonna', 'Ray of Light', 2),
     ('Secret', 1994, 'Madonna', 'Bedtime Stories', 2),
     ('Quit Playing Games (With My Heart)', 1996, 'Backstreet Boys', 'Backstreet Boys', 4),
     ('Everybody (Backstreet''s Back)', 1997, 'Backstreet Boys', 'Backstreet''s Back', 1),
     ('As Long as You Love Me', 1997, 'Backstreet Boys', 'Backstreet''s Back', 2),
     ('I Want It That Way', 1999, 'Backstreet Boys', 'Millennium', 1),
     ('Tearin'' Up My Heart', 1997, 'N''Sync', 'N''Sync', 2),
     ('I Want You Back', 1997, 'N''Sync', 'N''Sync', 1),
     ('(God Must Have Spent) A Little More Time on You', 1997, 'N''Sync', 'N''Sync', 6),
     ('Bye Bye Bye', 1999, 'N''Sync', 'No Strings Attached', 1)